07/28/2024 10:34:38 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_248_refine_6_7.py", line 150, in <module>
    raise NoAppException(
__main__.NoAppException: A valid Flask application was not obtained from 'mock_module:my_function()'.
Command exited with non-zero status 1
1.68user 4.79system 0:00.76elapsed 847%CPU (0avgtext+0avgdata 117112maxresident)k
0inputs+96outputs (0major+21698minor)pagefaults 0swaps
