07/28/2024 10:09:14 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_23_refine_3_1.py", line 49, in <module>
    request_close()
TypeError: <lambda>() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_23_refine_3_1.py", line 54, in <module>
    ctx = _cv_request.get()
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Command exited with non-zero status 1
1.70user 4.71system 0:00.70elapsed 915%CPU (0avgtext+0avgdata 111664maxresident)k
0inputs+72outputs (0major+26526minor)pagefaults 0swaps
