07/28/2024 10:54:01 AM Logging starts
Logging exception: (None, Exception('Test Exception'), None)
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_133_guide_2_1.py", line 93, in <module>
    server_error: t.Union[InternalServerError, ft.ResponseReturnValue]
NameError: name 'ft' is not defined
Command exited with non-zero status 1
1.66user 4.79system 0:00.74elapsed 869%CPU (0avgtext+0avgdata 117548maxresident)k
0inputs+64outputs (0major+21697minor)pagefaults 0swaps
